language: java
dist: trusty
jdk:
  - openjdk8

sudo: false

# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

#install: 

script:
  - ./gradlew clean jar
  - ./gradlew test
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'