language: java
jdk:
  - oraclejdk8

env:
   - COVERAGE=0.3

before_install:
  # execute all of the commands which need to be executed
  # before installing dependencies
  - pwd
  - ls -la

install:
  # install all of the dependencies you need here
  - ./gradlew clean jar

before_script:
  # execute all of the commands which need to be executed
  # before running actual tests

script:
  # execute all of the commands which should make the build pass or fail
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

#  If before_anything phase returns a non-zero exit code, the build is errored and stops immediately.
before_deploy:
  - ./gradlew test jacocoTestCoverageVerification

# branch: name of the branch. If omitted, this defaults to the app-specific branch, or master.
# If the branch name is not known ahead of time, you can specify  all_branches: true
deploy:
  provider: script
  script: echo 'WIP'
  on:
    all_branches: true